name: sodium_libs_platform_interface
description: flutter libraries for sodium
version: 0.1.0
homepage: https://github.com/Skycoder42/libsodium_dart_bindings

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  sodium: ^1.0.0

dev_dependencies:
  dart_pre_commit: ^2.3.1
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  mocktail: ^0.1.4

dependency_overrides:
  sodium:
    path: "../sodium"
