name: sodium_example
description: Sample dart program for web and native

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  sodium:
    path: ..

dev_dependencies:
  build_runner: ^1.12.2
  build_web_compilers: ^2.16.5
  lint: ^1.5.3

executables:
  native: main_native
