name: sodium

packages:
  # - packages/**
  - packages/sodium/*

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  coverage: ^1.0.2
  dart_pre_commit: ^2.2.0-nullsafety.2
  lint: ^1.5.3
  mocktail: ^0.1.1
  test: ^1.16.8
  tuple: ^2.0.0

scripts:
  get:
    run: dart pub global run melos exec -- make -f ../../Makefile get
    description: Run 'pub get' in all projects

  upgrade:
    run: dart pub global run melos exec -- make -f ../../Makefile upgrade
    description: Run 'pub upgrade' in all projects

  libsodium:fetch:
    run: dart run scripts/fetch_libsodium.dart
    description: Downloads all required libsodium binaries

  libsodium:fetch:linux:
    run: dart run scripts/fetch_libsodium.dart linux arch
    description: Downloads all required libsodium binaries (Linux only)

  libsodium:fetch:windows:
    run: dart run scripts/fetch_libsodium.dart windows
    description: Downloads all required libsodium binaries (Windows only)

  libsodium:fetch:macos:
    run: dart run scripts/fetch_libsodium.dart macos
    description: Downloads all required libsodium binaries (macOS only)

  libsodium:fetch:web:
    run: dart run scripts/fetch_libsodium.dart web
    description: Downloads all required libsodium binaries (Web only)

  analyze:
    run: dart pub global run melos exec -- make -f ../../Makefile analyze
    description: Run 'dart analyze' in all projects

  outdated:
    run: dart pub global run melos exec -- make -f ../../Makefile outdated
    description: Run 'pub outdated' in all projects

  build:
    run: dart pub global run melos exec -- make -f ../../Makefile build
    description: Run the build runner in all projects
    select-package:
      depends-on: build_runner

  build:clean:
    run: dart pub global run melos exec -- make -f ../../Makefile build-clean
    description: Run the build runner in all projects, discarding the previous state
    select-package:
      depends-on: build_runner

  test:
    run: dart pub global run melos exec -- make -f ../../Makefile test
    description: Run tests in all projects

  test:unit:
    run: dart pub global run melos exec -- make -f ../../Makefile unit-tests
    description: Run unit tests in all projects

  test:coverage:open:
    run: dart pub global run melos exec -- make -f ../../Makefile coverage-open
    description: Run tests in all projects

  test:integration:
    run: dart pub global run melos exec -- make -f ../../Makefile integration-tests
    description: Run integration tests in all projects

  verify:
    run: dart pub global run melos exec -c1 -- make -f ../../Makefile verify
    description: Verify all projects

  pre-commit:init:
    run: bash -c "echo -e '#!/bin/sh\nexec dart pub global run melos run pre-commit:run' > .git/hooks/pre-commit && chmod a+x .git/hooks/pre-commit"
    description: Setup pre commit hooks

  pre-commit:remove:
    run: rm -f .git/hooks/pre-commit
    description: Remove pre commit hooks

  pre-commit:run:
    run: dart pub global run melos exec -c1 -- dart pub run --no-sound-null-safety dart_pre_commit -oany -n -p --ansi
    description: Run pre commit hooks in all projects
