name: libsodium_flutter_bindings
description: A new flutter plugin project.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  libsodium_dart_bindings: ^1.0.0
  libsodium_flutter_bindings_linux: ^1.0.0
  libsodium_flutter_bindings_platform_interface: ^1.0.0
  libsodium_flutter_bindings_web: ^1.0.0
  libsodium_flutter_bindings_windows: ^1.0.0

dependency_overrides:
  libsodium_dart_bindings:
    path: "../libsodium_dart_bindings"
  libsodium_flutter_bindings_linux:
    path: "../libsodium_flutter_bindings_linux"
  libsodium_flutter_bindings_platform_interface:
    path: "../libsodium_flutter_bindings_platform_interface"
  libsodium_flutter_bindings_web:
    path: "../libsodium_flutter_bindings_web"
  libsodium_flutter_bindings_windows:
    path: "../libsodium_flutter_bindings_windows"

dev_dependencies:
  dart_pre_commit: ^2.2.0-nullsafety.2
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  mocktail: ^0.1.1

flutter:
  plugin:
    platforms:
      linux:
        default_package: libsodium_flutter_bindings_linux
      web:
        default_package: libsodium_flutter_bindings_web
      windows:
        default_package: libsodium_flutter_bindings_windows
