name: sodium_libs_example
publish_to: none
description: Demonstrates how to use the sodium_libs plugin.
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  cupertino_icons: ^1.0.2
  flutter: 
    sdk: flutter
  sodium_libs: 
    path: ../
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
