name: sodium_libs_example
description: Demonstrates how to use the sodium_libs plugin.
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  sodium_libs:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  lint: ^1.5.3

dependency_overrides:
  sodium:
    path: "../../sodium"

flutter:
  uses-material-design: true
