name: sodium_libs_windows
description: flutter windows libraries for sodium
version: 0.1.0

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  sodium: ^0.2.4
  sodium_libs_platform_interface: ^0.1.0

dev_dependencies:
  dart_pre_commit: ^2.3.1
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  mocktail: ^0.1.4

dependency_overrides:
  sodium:
    path: "../sodium"
  sodium_libs_platform_interface:
    path: "../sodium_libs_platform_interface"

flutter:
  plugin:
    platforms:
      windows:
        dartPluginClass: SodiumWindows
        pluginClass: SodiumLibsWindowsPlugin
