name: libsodium_flutter_bindings_example
description: Demonstrates how to use the libsodium_flutter_bindings plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  libsodium_dart_bindings: ^1.0.0
  libsodium_flutter_bindings:
    path: ../

dependency_overrides:
  libsodium_dart_bindings:
    path: ../../libsodium_dart_bindings
  libsodium_flutter_bindings_platform_interface:
    path: ../../libsodium_flutter_bindings_platform_interface
  libsodium_flutter_bindings_linux:
    path: ../../libsodium_flutter_bindings_linux

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
