name: sodium_libs
version: 0.1.0
description: flutter libraries for sodium

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  platform_info: ^3.1.0
  plugin_platform_interface: ^2.0.0
  sodium: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_pre_commit: ^2.3.1
  lint: ^1.5.3
  mocktail: ^0.1.4

dependency_overrides:
  sodium:
    path: "../sodium"

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: SodiumLibsWindowsPlugin
