name: sodium_libs
version: 1.1.1
description: Flutter companion package to sodium that provides the low-level libsodium binaries for easy use.
homepage: https://github.com/Skycoder42/libsodium_dart_bindings

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3
  meta: ^1.7.0
  plugin_platform_interface: ^2.0.2
  sodium: ^1.1.2
  synchronized: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_pre_commit: ^2.3.2
  lint: ^1.7.2

dependency_overrides:
  sodium:
    path: "../sodium"

executables:
  update_web: update_web

flutter:
  plugin:
    platforms:
      android:
        package: de.skycoder42.sodium_libs
        pluginClass: SodiumLibsPlugin
      ios:
        pluginClass: SodiumLibsPlugin
      linux:
        pluginClass: SodiumLibsPlugin
      windows:
        pluginClass: SodiumLibsPlugin
      macos:
        pluginClass: SodiumLibsPlugin
      web:
        fileName: src/platforms/sodium_web.dart
        pluginClass: SodiumWeb
