name: sodium_libs
version: 1.2.1
description: Flutter companion package to sodium that provides the low-level libsodium binaries for easy use.
homepage: https://github.com/Skycoder42/libsodium_dart_bindings

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3
  meta: ^1.7.0
  plugin_platform_interface: ^2.1.2
  sodium: ^1.2.0+2
  synchronized: ^3.0.0

dev_dependencies:
  args: ^2.3.0
  dart_pre_commit: ^2.3.3
  dart_test_tools: ^2.0.2
  flutter_test:
    sdk: flutter

dependency_overrides:
  sodium:
    path: "../sodium"

executables:
  update_web: update_web

flutter:
  plugin:
    platforms:
      android:
        package: de.skycoder42.sodium_libs
        pluginClass: SodiumLibsPlugin
        dartPluginClass: SodiumAndroid
      ios:
        pluginClass: SodiumLibsPlugin
        dartPluginClass: SodiumIos
      linux:
        pluginClass: SodiumLibsPlugin
        dartPluginClass: SodiumLinux
      windows:
        pluginClass: SodiumLibsPlugin
        dartPluginClass: SodiumWindows
      macos:
        pluginClass: SodiumLibsPlugin
        dartPluginClass: SodiumMacos
      web:
        fileName: src/platforms/sodium_web.dart
        pluginClass: SodiumWeb
