name: libsodium_flutter_bindings_macos
description: A new flutter plugin project.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    implements: libsodium_flutter_bindings
    platforms:
      macos:
        dartPluginClass: LibsodiumLinuxPlugin
        pluginClass: LibsodiumFlutterBindingsMacosPlugin

dependencies:
  flutter:
    sdk: flutter
  sodium: ^1.0.0
  libsodium_flutter_bindings_platform_interface: ^1.0.0

dependency_overrides:
  sodium:
    path: "../sodium"
  libsodium_flutter_bindings_platform_interface:
    path: "../libsodium_flutter_bindings_platform_interface"

dev_dependencies:
  dart_pre_commit: ^2.2.0-nullsafety.2
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  mocktail: ^0.1.1
