name: libsodium_dart_bindings_example
description: Sample dart program for web and native

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  libsodium_dart_bindings:
    path: ..

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  lint: ^1.5.3

executables:
  native: main_native
