include: package:lint/analysis_options_package.yaml

analyzer:
  exclude:
    - "**/*.ffi.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - "example/web/**"
    - "test/integration/js_test_common.dart"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_return: error
    missing_required_param: error

linter:
  rules:
    cascade_invocations: true
    close_sinks: true
    lines_longer_than_80_chars: true
    omit_local_variable_types: true
    only_throw_errors: true
    prefer_adjacent_string_concatenation: true
    prefer_expression_function_bodies: true
    prefer_single_quotes: true
    unawaited_futures: true
    always_use_package_imports: false
    prefer_relative_imports: true
