include: package:dart_test_tools/analysis_options_package.yaml

analyzer:
  exclude:
    - "**/*.ffi.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - "example/web/**"
    - "test/integration/js_test_common.dart"
