name: sodium
description: Dart bindings for libsodium, for the Dart-VM and for the Web
version: 1.2.0
homepage: https://github.com/Skycoder42/libsodium_dart_bindings

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  ffi: ^1.1.2
  freezed_annotation: ^1.1.0
  js: ^0.6.3
  meta: ^1.7.0

dev_dependencies:
  args: ^2.3.0
  build_runner: ^2.1.7
  coverage: ^1.0.4
  dart_pre_commit: ^2.3.3
  ffigen: ^4.1.2
  freezed: ^1.1.1
  lint: ^1.8.1
  mocktail: ^0.2.0
  path: ^1.8.1
  test: ^1.20.1
  tuple: ^2.0.0

ffigen:
  output: "lib/src/ffi/bindings/libsodium.ffi.dart"
  name: LibSodiumFFI
  description: "Bindings of libsodium"
  headers:
    entry-points:
      - "/usr/include/sodium.h"
  compiler-opts:
    - "-I/usr/lib/clang/13.0.0/include/"
  functions:
    include:
      - sodium.*
      - crypto.*
      - randombytes.*
