name: sodium
description: Dart bindings for libsodium, for the Dart-VM and for the Web
version: 0.2.4
homepage: https://github.com/Skycoder42/libsodium_dart_bindings

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  ffi: ^1.1.2
  freezed_annotation: ^0.14.2
  js: ^0.6.3
  meta: ^1.3.0

dev_dependencies:
  build_runner: ^2.0.4
  coverage: ^1.0.3
  dart_pre_commit: ^2.3.1
  ffigen: ^3.0.0
  freezed: ^0.14.2
  lint: ^1.5.3
  mocktail: ^0.1.4
  path: ^1.8.0
  test: ^1.17.8
  tuple: ^2.0.0

ffigen:
  output: "lib/src/ffi/bindings/libsodium.ffi.dart"
  name: LibSodiumFFI
  description: "Bindings of libsodium"
  headers:
    entry-points:
      - "/usr/include/sodium.h"
  compiler-opts:
    - "-I/usr/lib/clang/11.1.0/include/"
  functions:
    include:
      - sodium.*
      - crypto.*
      - randombytes.*
