name: sodium
description: Dart bindings for libsodium, for the Dart-VM and for the Web
version: 1.1.2
homepage: https://github.com/Skycoder42/libsodium_dart_bindings

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  ffi: ^1.1.2
  freezed_annotation: ^0.14.3
  js: ^0.6.3
  meta: ^1.7.0

dev_dependencies:
  args: ^2.3.0
  build_runner: ^2.1.2
  coverage: ^1.0.3
  dart_pre_commit: ^2.3.2
  ffigen: ^4.0.0
  freezed: ^0.14.5
  lint: ^1.7.2
  mocktail: ^0.1.4
  path: ^1.8.0
  test: ^1.17.12
  tuple: ^2.0.0

ffigen:
  output: "lib/src/ffi/bindings/libsodium.ffi.dart"
  name: LibSodiumFFI
  description: "Bindings of libsodium"
  headers:
    entry-points:
      - "/usr/include/sodium.h"
  compiler-opts:
    - "-I/usr/lib/clang/12.0.1/include/"
  functions:
    include:
      - sodium.*
      - crypto.*
      - randombytes.*
