name: libsodium_dart_bindings
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ffi: ^1.0.0

dev_dependencies:
  coverage: ^1.0.2
  dart_pre_commit: ^2.2.0-nullsafety.2
  ffigen: ^2.4.1
  lint: ^1.5.3
  mocktail: ^0.1.1
  test: ^1.16.8

ffigen:
  output: 'lib/src/sodium.ffi.dart'
  name: SodiumFFI
  description: 'Bindings of libsodium'
  headers:
    entry-points:
      - '/usr/include/sodium.h'
  compiler-opts:
    - '-I/usr/lib/clang/11.1.0/include/'
  functions:
    include:
      - sodium.*
      - crypto.*
      - randombytes.*