name: CI/CD for sodium

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    paths:
      - "packages/sodium/**"
      - ".github/workflows/sodium_ci.yaml"
  pull_request:
    branches:
      - "*"
    paths:
      - "packages/sodium/**"
      - ".github/workflows/sodium_ci.yaml"

jobs:
  ci:
    name: Contintues Integration
    uses: Skycoder42/dart_test_tools/.github/workflows/dart.yml@main
    with:
      workingDirectory: packages/sodium
      buildRunner: true
      publishExclude: '["lib/src/.gitignore"]'
      unitTestPaths: test/unit
      coverageExclude: >-
        "**/*.freezed.dart"
        "**/*.ffi.dart"
        "**/*.js.dart"
      integrationTestPaths: test/integration
      integrationTestSetup: >-
        {
          "linux": "sudo apt-get -qq install libsodium-dev",
          "windows": "choco install minisign -y && dart run tool/setup_windows_integration_tests.dart",
          "macos": "brew install libsodium",
          "web": "dart run tool/setup_web_integration_tests.dart"
        }

  cd:
    name: Contintues Deployment
    uses: Skycoder42/dart_test_tools/.github/workflows/publish.yml@main
    needs:
      - ci
    with:
      workingDirectory: packages/sodium
      buildRunner: true
      publishExclude: '["lib/src/.gitignore"]'
      tagPrefix: sodium/v
    secrets:
      PUB_DEV_CREDENTIALS: ${{ secrets.PUB_DEV_CREDENTIALS }}
