name: Continous Integration for package sodium

on:
  push:
    branches:
      - "*"
    paths:
      - "packages/sodium/**"
      - ".github/workflows/sodium_ci.yaml"
  pull_request:
    branches:
      - "*"
    paths:
      - "packages/sodium/**"
      - ".github/workflows/sodium_ci.yaml"

defaults:
  run:
    working-directory: packages/sodium

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux
          - windows
          - macos
          - web

        include:
          - platform: linux
            os: ubuntu-latest
            system: vm
          - platform: windows
            os: windows-latest
            system: vm
          - platform: macos
            os: macos-latest
            system: vm
          - platform: web
            os: ubuntu-latest
            system: js

    runs-on: ${{ matrix.os }}
    steps:
      - uses: dart-lang/setup-dart@v1
      - name: install libsodium
        if: matrix.platform == 'linux'
        run: |
          sudo apt-get -qq updated
          sudo apt-get -qq install libsodium-dev
      - name: install libsodium
        if: matrix.platform == 'macos'
        run: brew install libsodium
      - uses: actions/checkout@v2
      - name: fetch libsodium
        run: dart run scripts/fetch_libsodium.dart ${{ matrix.platform }}
        working-directory: .
      - run: make -f ../../Makefile get
      - run: make -f ../../Makefile analyze
      - run: make -f ../../Makefile unit-tests-${{ matrix.system }}-coverage
      - run: make -f ../../Makefile integration-tests-${{ matrix.system }}
      - uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: packages/sodium/coverage/lcov.info
          min_coverage: 95
          exclude: |
            **/*.ffi.dart 
            **/*.js.dart 
      - run: make -f ../../Makefile publish-dry

  release:
    runs-on: ubuntu-latest
    needs:
      - test
    if: github.ref == 'refs/heads/master'
    outputs:
      update: ${{ steps.version.outputs.update }}
      tag_name: ${{ steps.version.outputs.tag_name }}
    steps:
      - uses: dart-lang/setup-dart@v1
      - uses: actions/checkout@v2
      - uses: Skycoder42/action-dart-release@v1
        id: version
      - name: Create Release
        if: steps.version.outputs.update == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.tag_name }}
          release_name: ${{ steps.version.outputs.release_name }}
          body_path: ${{ steps.version.outputs.body_path }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - release
    if: needs.release.outputs.update == 'true'
    steps:
      - uses: dart-lang/setup-dart@v1
      - uses: actions/checkout@v2
      - run: make -f ../../Makefile get
      - name: store credentials
        run: |
          mkdir -p ~/.pub-cache
          echo '${{ secrets.PUB_DEV_CREDENTIALS }}' > ~/.pub-cache/credentials.json
      - run: make -f ../../Makefile publish
      - name: clean up credentials
        if: always()
        run: shred -fzvu ~/.pub-cache/credentials.json

  doc:
    runs-on: ubuntu-latest
    needs:
      - release
    if: needs.release.outputs.update == 'true'
    steps:
      - uses: dart-lang/setup-dart@v1
      - uses: actions/checkout@v2
      - run: make -f ../../Makefile get
      - run: make -f ../../Makefile doc
      - name: upload doc
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/api
          commit_message: Updated documentation to v${{ needs.release.outputs.tag_name }}
